import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy | Whatsy",
  description:
    "Privacy Policy for Whatsy, including local-first processing, waitlist data, and user-managed security responsibilities.",
};

const sections = [
  {
    title: "1. Overview",
    paragraphs: [
      "Whatsy is designed as a local-first product. Its core purpose is to help users manage conversations using software, workflows, and models that are intended to run on user-controlled devices rather than on Whatsy-managed cloud infrastructure.",
      "This Privacy Policy explains how we handle information when you use the Whatsy website, join the waitlist, or use the product. It also explains an important principle of the product: because Whatsy may rely on local models, local storage, and user-managed environments, privacy and security depend in part on how you configure, secure, and operate your own device, accounts, and software stack.",
    ],
  },
  {
    title: "2. Information We Collect",
    paragraphs: [
      "We collect limited information that you voluntarily provide to us through the website. For example, if you join the waitlist, contact us, or otherwise submit information through our website, we may collect your name, email address, or the contents of your message.",
      "We do not state that Whatsy collects in-product conversation content, prompts, or LLM outputs by default for cloud processing. Based on the current product direction, Whatsy is intended to operate locally and without cloud LLM processing by default.",
    ],
    bullets: [
      "Waitlist or contact information you choose to submit",
      "Basic website request information that may be generated by your browser or hosting provider",
      "Operational information required to maintain and secure the website itself",
    ],
  },
  {
    title: "3. Local Processing And Device Storage",
    paragraphs: [
      "A central part of Whatsy’s privacy model is that message handling, prompt construction, local model inference, drafts, and related workflow data may be stored or processed on your own device or within software you choose to run locally.",
      "When data stays on your machine, that data is not automatically under our custody. As a result, we are not responsible for the security of your computer, mobile device, browser profile, local model runtime, local database, exported files, or any third-party tools you install to support your use of Whatsy.",
    ],
  },
  {
    title: "4. Third-Party Services And User-Connected Tools",
    paragraphs: [
      "If you connect or interact with third-party services, messaging platforms, browser automation tools, model runtimes, extensions, or hosting tools, your use of those services is governed by their own terms and privacy practices.",
      "We are not responsible for the privacy, retention, security, or operational practices of third parties that you choose to use alongside Whatsy. You are responsible for reviewing those third-party terms, permissions, and policies before enabling them.",
    ],
  },
  {
    title: "5. How We Use Information",
    paragraphs: [
      "We use the limited information you submit through the website to operate the site, manage the waitlist, respond to inquiries, communicate about the product, improve our offering, and protect the security and integrity of the website and our business.",
      "We do not use locally processed message content or locally generated outputs for cloud model training simply because they exist on your device. If we introduce hosted features or data collection practices in the future, we may update this policy before or when those features become available.",
    ],
  },
  {
    title: "6. Security And User Responsibilities",
    paragraphs: [
      "We take reasonable steps to protect the website and any information you deliberately submit to us through it. However, no website, application, or communication method is completely secure.",
      "Because Whatsy is intended to operate in local and user-controlled environments, you are responsible for maintaining the security and privacy of your own setup.",
    ],
    bullets: [
      "Use strong passwords, device encryption, and appropriate access controls",
      "Keep your operating system, browser, and local model tooling updated",
      "Protect API keys, integrations, credentials, exported files, and backups",
      "Limit access to devices or environments where Whatsy or related local data is stored",
      "Review outputs before sending or acting on them",
    ],
  },
  {
    title: "7. Data Sharing",
    paragraphs: [
      "We do not sell your personal information. We may disclose limited information if required to comply with law, enforce our rights, protect our users, investigate abuse, or support a business transaction such as a merger, acquisition, or asset sale.",
      "If you choose to share, export, transmit, or publish content generated through Whatsy, that sharing happens under your direction and responsibility.",
    ],
  },
  {
    title: "8. Retention",
    paragraphs: [
      "We retain website-submitted information only for as long as reasonably necessary for the purposes described in this policy, including waitlist management, communications, legal compliance, dispute resolution, and security.",
      "Data stored locally as part of your use of Whatsy may remain on your own device until you delete it. You are responsible for managing local retention, backups, and deletion in your own environment.",
    ],
  },
  {
    title: "9. International Use",
    paragraphs: [
      "If you access the website from outside the country in which our website infrastructure or operations are based, your information may be processed in jurisdictions with different data protection laws than your home jurisdiction.",
      "You are responsible for ensuring that your own use of Whatsy, local models, and messaging workflows complies with applicable laws and regulations in your jurisdiction.",
    ],
  },
  {
    title: "10. Changes To This Policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. When we do, we will update the effective date on this page and may provide additional notice where appropriate.",
      "Your continued use of the website or Whatsy after a revised policy becomes effective means you accept the updated policy.",
    ],
  },
  {
    title: "11. Contact",
    paragraphs: [
      "If you have questions about this Privacy Policy or want to contact us about privacy matters, please use the official contact channel or support details made available through the Whatsy website at the time of your request.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      description="How Whatsy handles information, what stays local, and where responsibility shifts to users when they run their own local models, devices, and supporting tools."
      effectiveDate="March 14, 2026"
      sections={sections}
    />
  );
}
